config/routes.rb
Rails.application.routes.draw do
  get 'quotes/index'
  resources :quotes

  root "quotes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path, notice: "Quote was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @quote.destroy
    redirect_to quotes_path, notice: "Quote was successfully destroyed."
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-50 max-w-full overflow-x-hidden font-['ubuntu']">
    <main class="w-5/6 mx-auto h-screen my-12 bg-gray-200 p-12 rounded-lg">
      <%= yield %>
    </main>
  </body>
</html>

app/views/quotes/index.html.erb
<div class="bg-gray-300 rounded-lg py-3 px-6 grid grid-cols-2 gap-2">
  <div class="text-lg py-1">
    Quotes
  </div>
  <div class="flex justify-end">
    <%= link_to "New quote", new_quote_path, class: "bg-slate-800 text-gray-200 px-4  text-sm rounded-md hover:opacity-75 flex items-center" %>
  </div>
</div>
<div class="bg-gray-300 rounded-lg py-3 px-6 my-6 h-[80%]">
  <%= render @quotes %>
</div>